"""
ETF Monitor seed data: tickers + descriptions from the user's screenshots.
'category' = '분류' (top-level grouping)
'sector'   = a normalized chip color group (섹터 ETF는 테마, 국가 ETF는 지역)
'description' = '투자 대상/섹터' or '주요 테마/설명' from the screenshot
'yf_ticker' = symbol used for Yahoo Finance fetching (Korean codes get .KS)
"""

ETFS = [
    # ── 국가/지역 ──
    {"category": "국가/지역", "ticker": "SPY",  "name": "SPDR S&P 500 ETF Trust",            "description": "미국 (대형주)",    "sector": "미국"},
    {"category": "국가/지역", "ticker": "MDY",  "name": "SPDR S&P MidCap 400 ETF Trust",     "description": "미국 (중형주)",    "sector": "미국"},
    {"category": "국가/지역", "ticker": "EWT",  "name": "iShares MSCI Taiwan ETF",           "description": "대만",            "sector": "아시아"},
    {"category": "국가/지역", "ticker": "EWJ",  "name": "iShares MSCI Japan ETF",            "description": "일본",            "sector": "아시아"},
    {"category": "국가/지역", "ticker": "VWO",  "name": "Vanguard FTSE Emerging Markets ETF","description": "신흥국 (전체)",   "sector": "신흥국"},
    {"category": "국가/지역", "ticker": "MCHI", "name": "iShares MSCI China ETF",            "description": "중국",            "sector": "아시아"},
    {"category": "국가/지역", "ticker": "INDA", "name": "iShares MSCI India ETF",            "description": "인도",            "sector": "아시아"},
    {"category": "국가/지역", "ticker": "EWU",  "name": "iShares MSCI United Kingdom ETF",   "description": "영국",            "sector": "유럽"},
    {"category": "국가/지역", "ticker": "EWQ",  "name": "iShares MSCI France ETF",           "description": "프랑스",          "sector": "유럽"},
    {"category": "국가/지역", "ticker": "EWG",  "name": "iShares MSCI Germany ETF",          "description": "독일",            "sector": "유럽"},
    {"category": "국가/지역", "ticker": "ILF",  "name": "iShares Latin America 40 ETF",      "description": "라틴 아메리카",   "sector": "신흥국"},
    {"category": "국가/지역", "ticker": "EWA",  "name": "iShares MSCI Australia ETF",        "description": "호주",            "sector": "오세아니아"},
    {"category": "국가/지역", "ticker": "EWC",  "name": "iShares MSCI Canada ETF",           "description": "캐나다",          "sector": "북미"},

    # ── 섹터/테마 (US/Global) ──
    {"category": "섹터/테마", "ticker": "SMH",  "name": "VanEck Semiconductor ETF",                       "description": "반도체",            "sector": "반도체"},
    {"category": "섹터/테마", "ticker": "OIH",  "name": "VanEck Oil Services ETF",                        "description": "유전 서비스",       "sector": "에너지"},
    {"category": "섹터/테마", "ticker": "VHT",  "name": "Vanguard Health Care ETF",                       "description": "헬스케어",          "sector": "헬스케어"},
    {"category": "섹터/테마", "ticker": "ITA",  "name": "iShares U.S. Aerospace & Defense ETF",           "description": "방산 및 우주",      "sector": "방산/우주"},
    {"category": "섹터/테마", "ticker": "XLK",  "name": "Technology Select Sector SPDR Fund",             "description": "기술주 (IT)",       "sector": "IT/기술"},
    {"category": "섹터/테마", "ticker": "XLI",  "name": "Industrial Select Sector SPDR Fund",             "description": "산업재",            "sector": "산업재"},
    {"category": "섹터/테마", "ticker": "IBB",  "name": "iShares Biotechnology ETF",                      "description": "바이오테크",        "sector": "바이오/제약"},
    {"category": "섹터/테마", "ticker": "XOP",  "name": "SPDR S&P Oil & Gas Exploration & Production",    "description": "석유/가스 탐사",    "sector": "에너지"},
    {"category": "섹터/테마", "ticker": "XLV",  "name": "Health Care Select Sector SPDR Fund",            "description": "헬스케어",          "sector": "헬스케어"},
    {"category": "섹터/테마", "ticker": "XBI",  "name": "SPDR S&P Biotech ETF",                           "description": "바이오테크 (중소형)","sector": "바이오/제약"},
    {"category": "섹터/테마", "ticker": "IAK",  "name": "iShares U.S. Insurance ETF",                     "description": "보험",              "sector": "금융"},
    {"category": "섹터/테마", "ticker": "XME",  "name": "SPDR S&P Metals & Mining ETF",                   "description": "금속 및 광업",      "sector": "소재/광업"},
    {"category": "섹터/테마", "ticker": "XLY",  "name": "Consumer Discretionary Select Sector SPDR",      "description": "임의소비재",        "sector": "임의소비재"},
    {"category": "섹터/테마", "ticker": "XLC",  "name": "Communication Services Select Sector SPDR",      "description": "통신 서비스",       "sector": "통신"},
    {"category": "섹터/테마", "ticker": "VGT",  "name": "Vanguard Information Technology ETF",            "description": "IT 기술",          "sector": "IT/기술"},
    {"category": "섹터/테마", "ticker": "PPH",  "name": "VanEck Pharmaceutical ETF",                      "description": "제약",              "sector": "바이오/제약"},
    {"category": "섹터/테마", "ticker": "GDX",  "name": "VanEck Gold Miners ETF",                         "description": "금광업",            "sector": "소재/광업"},
    {"category": "섹터/테마", "ticker": "VNQ",  "name": "Vanguard Real Estate ETF",                       "description": "부동산 (리츠)",     "sector": "부동산/리츠"},
    {"category": "섹터/테마", "ticker": "COPX", "name": "Global X Copper Miners ETF",                     "description": "구리 채굴",         "sector": "소재/광업"},
    {"category": "섹터/테마", "ticker": "LIT",  "name": "Global X Lithium & Battery Tech ETF",            "description": "리튬 및 2차전지",   "sector": "2차전지"},
    {"category": "섹터/테마", "ticker": "ITB",  "name": "iShares U.S. Home Construction ETF",             "description": "주택 건설",         "sector": "건설/부동산"},
    {"category": "섹터/테마", "ticker": "IGV",  "name": "iShares Expanded Tech-Software Sector ETF",      "description": "소프트웨어",        "sector": "IT/기술"},
    {"category": "섹터/테마", "ticker": "XLP",  "name": "Consumer Staples Select Sector SPDR Fund",       "description": "필수소비재",        "sector": "필수소비재"},
    {"category": "섹터/테마", "ticker": "KBWB", "name": "Invesco KBW Bank ETF",                           "description": "은행",              "sector": "금융"},
    {"category": "섹터/테마", "ticker": "XRT",  "name": "SPDR S&P Retail ETF",                            "description": "소매 유통",         "sector": "임의소비재"},
    {"category": "섹터/테마", "ticker": "SLV",  "name": "iShares Silver Trust",                           "description": "은 (원자재)",       "sector": "원자재"},
    {"category": "섹터/테마", "ticker": "IYT",  "name": "iShares U.S. Transportation ETF",                "description": "운송",              "sector": "운송"},
    {"category": "섹터/테마", "ticker": "KRE",  "name": "SPDR S&P Regional Banking ETF",                  "description": "지역 은행",         "sector": "금융"},
    {"category": "섹터/테마", "ticker": "IGF",  "name": "iShares Global Infrastructure ETF",              "description": "글로벌 인프라",     "sector": "인프라"},
    {"category": "섹터/테마", "ticker": "TAN",  "name": "Invesco Solar ETF",                              "description": "태양광 에너지",     "sector": "신재생에너지"},
    {"category": "섹터/테마", "ticker": "XLE",  "name": "Energy Select Sector SPDR Fund",                 "description": "에너지",            "sector": "에너지"},
    {"category": "섹터/테마", "ticker": "PAVE", "name": "Global X U.S. Infrastructure Development ETF",   "description": "미국 인프라 개발",  "sector": "인프라"},
    {"category": "섹터/테마", "ticker": "URA",  "name": "Global X Uranium ETF",                           "description": "우라늄",            "sector": "원자력"},
    {"category": "섹터/테마", "ticker": "XLB",  "name": "Materials Select Sector SPDR Fund",              "description": "소재",              "sector": "소재/광업"},
    {"category": "섹터/테마", "ticker": "IHF",  "name": "iShares U.S. Healthcare Providers ETF",          "description": "의료 서비스 제공",  "sector": "헬스케어"},
    {"category": "섹터/테마", "ticker": "XLF",  "name": "Financial Select Sector SPDR Fund",              "description": "금융",              "sector": "금융"},
    {"category": "섹터/테마", "ticker": "SOCL", "name": "Global X Social Media ETF",                      "description": "소셜 미디어",       "sector": "통신"},
    {"category": "섹터/테마", "ticker": "XLU",  "name": "Utilities Select Sector SPDR Fund",              "description": "유틸리티",          "sector": "유틸리티"},
    {"category": "섹터/테마", "ticker": "CTEX", "name": "ProShares S&P Kensho Cleantech ETF",             "description": "클린테크",          "sector": "신재생에너지"},
    {"category": "섹터/테마", "ticker": "BOTZ", "name": "Global X Robotics & Artificial Intelligence ETF","description": "로봇 및 AI",       "sector": "AI/로봇"},
    {"category": "섹터/테마", "ticker": "DTCR", "name": "iShares Data Center REITs & Digital Infra",      "description": "데이터센터 리츠",   "sector": "부동산/리츠"},
    {"category": "섹터/테마", "ticker": "BUG",  "name": "Global X Cybersecurity ETF",                     "description": "사이버 보안",       "sector": "IT/기술"},
    {"category": "섹터/테마", "ticker": "ICLN", "name": "iShares Global Clean Energy ETF",                "description": "글로벌 친환경 에너지","sector": "신재생에너지"},
    {"category": "섹터/테마", "ticker": "UNG",  "name": "United States Natural Gas Fund",                 "description": "천연가스 (원자재)",  "sector": "원자재"},
    {"category": "섹터/테마", "ticker": "RTH",  "name": "VanEck Retail ETF",                              "description": "소매업",            "sector": "임의소비재"},
    {"category": "섹터/테마", "ticker": "EXI",  "name": "iShares Global Industrials ETF",                 "description": "글로벌 산업재",     "sector": "산업재"},
    {"category": "섹터/테마", "ticker": "SRVR", "name": "Pacer Benchmark Data & Infrastructure Real Estate","description": "데이터 인프라 리츠","sector": "부동산/리츠"},
    {"category": "섹터/테마", "ticker": "PBJ",  "name": "Invesco Food & Beverage ETF",                    "description": "식음료",            "sector": "필수소비재"},
    {"category": "섹터/테마", "ticker": "HERO", "name": "Global X Video Games & Esports ETF",             "description": "게임 및 e스포츠",   "sector": "게임/엔터"},
    {"category": "섹터/테마", "ticker": "354350.KS", "name": "HANARO 글로벌 럭셔리 S&P",                  "description": "글로벌 명품/럭셔리", "sector": "럭셔리"},
    {"category": "섹터/테마", "ticker": "GNOM", "name": "Global X Genomics & Biotechnology ETF",          "description": "유전학 및 바이오",  "sector": "바이오/제약"},
    {"category": "섹터/테마", "ticker": "442320.KS", "name": "KBSTAR 글로벌 원자력 iSelect",              "description": "글로벌 원자력",     "sector": "원자력"},

    # ── 한국주식 ETF ──
    {"category": "한국 ETF", "ticker": "495850.KS", "name": "SAMSUNG KODEX KOREA Value-up ETF",                    "description": "코리아 밸류업",            "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "494670.KS", "name": "MIRAE ASSET TIGER Shipbuilding TOP10 ETF",            "description": "조선 TOP10",              "sector": "조선"},
    {"category": "한국 ETF", "ticker": "491820.KS", "name": "NH-Amundi HANARO Electric Power Capex ETF",           "description": "전력 설비 투자",          "sector": "전력/인프라"},
    {"category": "한국 ETF", "ticker": "487240.KS", "name": "SAMSUNG KODEX AI Electric Power Core Facilities ETF", "description": "AI 전력 핵심 설비",       "sector": "전력/인프라"},
    {"category": "한국 ETF", "ticker": "475050.KS", "name": "KIM ACE KPOP Focus ETF",                              "description": "KPOP 포커스",             "sector": "엔터/콘텐츠"},
    {"category": "한국 ETF", "ticker": "471990.KS", "name": "SAMSUNG KODEX AI Semiconductor Core Equipment ETF",   "description": "AI 반도체 핵심 장비",     "sector": "반도체"},
    {"category": "한국 ETF", "ticker": "466940.KS", "name": "MIRAE ASSET TIGER Bank High Dividend Plus TOP 10 ETF","description": "은행 고배당 플러스",      "sector": "금융/배당"},
    {"category": "한국 ETF", "ticker": "463250.KS", "name": "MIRAE ASSET TIGER K-DEFENSE INDUSTRY & SPACE ETF",    "description": "K-방산 및 우주",          "sector": "방산/우주"},
    {"category": "한국 ETF", "ticker": "449450.KS", "name": "Hanwha PLUS K-Defense Industry ETF",                  "description": "K-방산",                  "sector": "방산/우주"},
    {"category": "한국 ETF", "ticker": "447430.KS", "name": "KIM ACE Next level Value Active ETF",                 "description": "가치주 액티브",           "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "445290.KS", "name": "SAMSUNG KODEX Robot Active ETF",                      "description": "로봇 액티브",             "sector": "AI/로봇"},
    {"category": "한국 ETF", "ticker": "438900.KS", "name": "NH-Amundi HANARO K-Food ETF",                         "description": "K-푸드",                  "sector": "필수소비재"},
    {"category": "한국 ETF", "ticker": "434730.KS", "name": "NH-Amundi HANARO Nuclear Power",                     "description": "원자력",                  "sector": "원자력"},
    {"category": "한국 ETF", "ticker": "421320.KS", "name": "PLUS Aerospace & UAM iSelect ETF",                   "description": "우주항공 및 UAM",         "sector": "방산/우주"},
    {"category": "한국 ETF", "ticker": "395160.KS", "name": "SAMSUNG KODEX AI Semiconductor TOP2 Plus ETF",       "description": "AI 반도체 TOP2 플러스",   "sector": "반도체"},
    {"category": "한국 ETF", "ticker": "385510.KS", "name": "SAMSUNG KODEX Renewable Energy Active ETF",          "description": "신재생 에너지 액티브",    "sector": "신재생에너지"},
    {"category": "한국 ETF", "ticker": "364970.KS", "name": "Mirae Asset Tiger KRX Bio K-New Deal ETF",           "description": "바이오 K-뉴딜",           "sector": "바이오/제약"},
    {"category": "한국 ETF", "ticker": "329200.KS", "name": "MIRAE ASSET TIGER REITS REAL ESTATE INFRA ETF",      "description": "리츠 부동산 인프라",      "sector": "부동산/리츠"},
    {"category": "한국 ETF", "ticker": "307520.KS", "name": "MIRAE ASSET TIGER HOLDINGS COMPANY ETF",             "description": "지주회사",                "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "305720.KS", "name": "Samsung KODEX Secondary Battery Industry ETF",       "description": "2차전지 산업",            "sector": "2차전지"},
    {"category": "한국 ETF", "ticker": "300950.KS", "name": "Samsung KODEX Game Industry ETF",                    "description": "게임 산업",               "sector": "게임/엔터"},
    {"category": "한국 ETF", "ticker": "292150.KS", "name": "Mirae Asset TIGER Korea TOP10 ETF",                  "description": "국내 TOP10",              "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "266390.KS", "name": "SAMSUNG KODEX Consumer Discretionary ETF",           "description": "경기 소비재",             "sector": "임의소비재"},
    {"category": "한국 ETF", "ticker": "266360.KS", "name": "SAMSUNG KODEX K-Content ETF",                        "description": "K-콘텐츠",                "sector": "엔터/콘텐츠"},
    {"category": "한국 ETF", "ticker": "261140.KS", "name": "Mirae Asset Tiger Preferred Stock ETF",              "description": "우선주",                  "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "252650.KS", "name": "Samsung KODEX 200 Equalweight ETF",                  "description": "코스피 200 동일가중",     "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "244580.KS", "name": "Samsung KODEX BIO ETF",                              "description": "바이오",                  "sector": "바이오/제약"},
    {"category": "한국 ETF", "ticker": "229200.KS", "name": "SAMSUNG KODEX KOSDAQ 150 ETF",                       "description": "코스닥 150",              "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "228810.KS", "name": "MIRAE ASSET TIGER MEDIA CONTENTS ETF",               "description": "미디어 컨텐츠",           "sector": "엔터/콘텐츠"},
    {"category": "한국 ETF", "ticker": "228800.KS", "name": "MIRAE ASSET TIGER TOUR LEISURE ETF",                 "description": "여행 레저",               "sector": "임의소비재"},
    {"category": "한국 ETF", "ticker": "228790.KS", "name": "MIRAE ASSET TIGER COSMETICS ETF",                    "description": "화장품",                  "sector": "임의소비재"},
    {"category": "한국 ETF", "ticker": "161510.KS", "name": "Hanwha PLUS High Dividend ETF",                      "description": "고배당",                  "sector": "금융/배당"},
    {"category": "한국 ETF", "ticker": "157490.KS", "name": "Mirae Asset Tiger Software ETF",                     "description": "소프트웨어",              "sector": "IT/기술"},
    {"category": "한국 ETF", "ticker": "150460.KS", "name": "Mirae Asset Tiger China Consumer ETF",               "description": "중국 소비재",             "sector": "임의소비재"},
    {"category": "한국 ETF", "ticker": "143860.KS", "name": "Mirae Asset Tiger Health Care ETF",                  "description": "헬스케어",                "sector": "헬스케어"},
    {"category": "한국 ETF", "ticker": "140710.KS", "name": "Samsung KODEX Transportation ETF",                   "description": "운송",                    "sector": "운송"},
    {"category": "한국 ETF", "ticker": "140700.KS", "name": "Samsung KODEX Insurance ETF",                        "description": "보험",                    "sector": "금융"},
    {"category": "한국 ETF", "ticker": "139280.KS", "name": "Mirae Asset Tiger Consumer Staples ETF",             "description": "필수 소비재",             "sector": "필수소비재"},
    {"category": "한국 ETF", "ticker": "139270.KS", "name": "Mirae Asset Tiger Financials ETF",                   "description": "금융",                    "sector": "금융"},
    {"category": "한국 ETF", "ticker": "139260.KS", "name": "Mirae Asset Tiger IT ETF",                           "description": "IT",                      "sector": "IT/기술"},
    {"category": "한국 ETF", "ticker": "139230.KS", "name": "Mirae Asset TIGER 200 Heavy Industry",               "description": "200 중공업",              "sector": "산업재"},
    {"category": "한국 ETF", "ticker": "138540.KS", "name": "Mirae Asset Tiger Hyundai Motor Group ETF",          "description": "현대차 그룹",             "sector": "자동차"},
    {"category": "한국 ETF", "ticker": "117700.KS", "name": "Samsung KODEX Constructions ETF",                    "description": "건설",                    "sector": "건설/부동산"},
    {"category": "한국 ETF", "ticker": "117680.KS", "name": "Samsung KODEX Steels ETF",                           "description": "철강",                    "sector": "소재/광업"},
    {"category": "한국 ETF", "ticker": "117460.KS", "name": "Samsung KODEX Energy & Chemicals ETF",               "description": "에너지 화학",             "sector": "에너지"},
    {"category": "한국 ETF", "ticker": "102970.KS", "name": "Samsung KODEX Securities ETF",                       "description": "증권",                    "sector": "금융"},
    {"category": "한국 ETF", "ticker": "102960.KS", "name": "Samsung KODEX Machinery & Equipment ETF",            "description": "기계 장비",               "sector": "산업재"},
    {"category": "한국 ETF", "ticker": "102780.KS", "name": "Samsung KODEX Samsung Group ETF",                    "description": "삼성그룹",                "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "091180.KS", "name": "Samsung KODEX Autos ETF",                            "description": "자동차",                  "sector": "자동차"},
    {"category": "한국 ETF", "ticker": "091170.KS", "name": "Samsung KODEX Banks ETF",                            "description": "은행",                    "sector": "금융"},
    {"category": "한국 ETF", "ticker": "069500.KS", "name": "Samsung KODEX 200 ETF",                              "description": "코스피 200",              "sector": "한국 대표"},
    {"category": "한국 ETF", "ticker": "0105E0.KS", "name": "Shinhan SOL Korea High Dividend ETF",                "description": "국내 고배당",             "sector": "금융/배당"},
]

if __name__ == "__main__":
    print(f"Total ETFs: {len(ETFS)}")
    from collections import Counter
    c = Counter(e["category"] for e in ETFS)
    for k, v in c.items():
        print(f"  {k}: {v}")
